import { createFileRoute, Link, useNavigate } from '@tanstack/react-router';
import { useState } from 'react';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';
export const Route=createFileRoute('/auth')({component:Auth});
type Mode='email'|'id'|'signup';
const regions=['Centre','Hauts-Bassins','Boucle du Mouhoun','Cascades','Centre-Est','Centre-Nord','Centre-Ouest','Centre-Sud','Est','Nord','Plateau-Central','Sahel','Sud-Ouest'];
function Auth(){const nav=useNavigate();const[m,setM]=useState<Mode>('email');const[email,setEmail]=useState('');const[id,setId]=useState('');const[pwd,setPwd]=useState('');const[region,setRegion]=useState('');const[busy,setBusy]=useState(false);
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{if(m==='signup'){if(!email||!pwd||!region)throw Error('E-mail, mot de passe et région sont obligatoires.');const{data,error}=await supabase.auth.signUp({email:email.trim().toLowerCase(),password:pwd,options:{data:{region_name:region}}});if(error)throw error;toast.success(data.session?'Compte créé.':'Compte créé. Vérifie ton e-mail si la confirmation est activée.');if(data.session)nav({to:'/'});return}let loginEmail=email;if(m==='id'){const{data,error}=await(supabase as any).rpc('resolve_stuff_login',{p_stuff_id:id.trim().toUpperCase()});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(!row?.email)throw Error('Stuff ID introuvable.');loginEmail=row.email}const{error}=await supabase.auth.signInWithPassword({email:loginEmail.trim().toLowerCase(),password:pwd});if(error)throw error;toast.success('Connexion réussie.');nav({to:'/'});}catch(e:any){toast.error(e?.message||'Impossible de continuer.')}finally{setBusy(false)}}
return <main className="min-h-screen bg-background p-4"><div className="mx-auto max-w-md pt-8"><Link to="/" className="text-sm font-bold text-primary">← Accueil</Link><section className="mt-4 rounded-3xl border bg-card p-6"><b className="text-xs tracking-[.2em] text-primary">STUFF MARKET</b><h1 className="mt-2 text-2xl font-black">{m==='signup'?'Créer un compte':'Connexion'}</h1><div className="mt-5 grid grid-cols-3 gap-2">{([['email','E-mail'],['id','Stuff ID'],['signup','Inscription']] as const).map(([v,t])=><button key={v} type="button" onClick={()=>setM(v)} className={`rounded-xl border p-2 text-xs font-bold ${m===v?'bg-primary text-primary-foreground':''}`}>{t}</button>)}</div><form onSubmit={submit} className="mt-5 space-y-4">{m==='id'?<input className="w-full rounded-xl border p-3" placeholder="Stuff ID" value={id} onChange={e=>setId(e.target.value)}/>:<input type="email" className="w-full rounded-xl border p-3" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/>}<input type="password" className="w-full rounded-xl border p-3" placeholder="Mot de passe" value={pwd} onChange={e=>setPwd(e.target.value)}/>{m==='signup'&&<select className="w-full rounded-xl border p-3" value={region} onChange={e=>setRegion(e.target.value)}><option value="">Région</option>{regions.map(r=><option key={r}>{r}</option>)}</select>}<button disabled={busy} className="w-full rounded-xl bg-primary p-3 font-bold text-primary-foreground">{busy?'Patiente...':m==='signup'?'Créer mon compte':'Se connecter'}</button></form></section></div></main>}
